apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
# Deployments  Rolling Update
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  minReadySeconds: 30   
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd:2.4
        ports:
        - containerPort: 80
